TEXTS = {
    "ru": {
        "start": "Привет! Я бот «Мировая карта граффити» 🌍\n\nВыберите действие:",
        "btn_map": "🗺 Карта",
        "btn_add": "➕ Добавить граффити",
        "btn_search": "🔍 Поиск",
        "btn_manage": "⚙️ Управление",
        "btn_cancel": "❌ Отмена",
        "btn_language": "🌐 Язык",
        "btn_open_map": "🗺 Открыть карту",
        "send_photo": "📸 Отправьте фото граффити:",
        "send_location": "📍 Теперь отправьте геолокацию граффити.\n\nНажмите скрепку 📎 → Геолокация → выберите точку на карте.",
        "send_author": "✍️ Введите никнейм автора граффити (или напишите «нет», если неизвестен):",
        "send_date": "📅 Введите дату нанесения (например: 2024 или март 2024), или «нет»:",
        "send_description": "📝 Добавьте описание граффити (или «нет»):",
        "added": "✅ Граффити отправлено на модерацию! После проверки оно появится на карте.",
        "cancelled": "Действие отменено.",
        "no_graffiti": "На карте пока нет граффити. Добавьте первое!",
        "open_map": "Нажмите кнопку, чтобы открыть карту:",
        "search_prompt": "Введите имя автора или ключевое слово:",
        "search_empty": "По запросу «{}» ничего не найдено.",
        "search_found": "Найдено граффити: {}",
        "search_done": "Поиск завершён.",
        "send_photo_please": "Пожалуйста, отправьте именно фото.",
        "send_location_please": "Пожалуйста, отправьте именно геолокацию (📎 → Геолокация).",
        "admin_only": "Эта функция доступна только администратору.",
        "choose_language": "🌐 Choose language:",
        "language_set": "Язык установлен: Русский 🇷🇺",
        "no_description": "Нет описания",
        "graffiti_count": "На карте {} граффити:",
        "delete": "🗑 Удалить",
        "confirm_delete": "✅ Да, удалить",
        "cancel_delete_btn": "❌ Отмена",
        "deleted": "🗑 УДАЛЕНО",
        "approved": "✅ ОДОБРЕНО",
        "rejected": "❌ ОТКЛОНЕНО",
        "confirm_deletion": "Подтвердите удаление",
        "no": "нет",
        "unknown_author": "Неизвестен",
        "unknown_date": "Неизвестна",
        "btn_stats": "📊 Статистика",
        "stats": "📊 Статистика:\n\n🎨 На карте: {approved}\n⏳ На модерации: {pending}\n📦 Всего: {total}",
        "top_users": "\n\n🏆 Топ участников:",
        "users_count": "\n\n👥 Пользователей: {}",
        "top_liked": "\n\n❤️ Самые популярные:",
        "btn_gallery": "🖼 Галерея",
        "gallery_empty": "Граффити пока нет.",
        "gallery_counter": "{} из {}",
        "send_city": "🏙 Введите название города (например: Тбилиси, Берлин, Токио):",
    },
    "en": {
        "start": "Hello! I'm the «World Graffiti Map» bot 🌍\n\nChoose an action:",
        "btn_map": "🗺 Map",
        "btn_add": "➕ Add graffiti",
        "btn_search": "🔍 Search",
        "btn_manage": "⚙️ Manage",
        "btn_cancel": "❌ Cancel",
        "btn_language": "🌐 Language",
        "btn_open_map": "🗺 Open map",
        "send_photo": "📸 Send a photo of the graffiti:",
        "send_location": "📍 Now send the graffiti location.\n\nTap the clip 📎 → Location → choose a point on the map.",
        "send_author": "✍️ Enter the artist's name (or 'no' if unknown):",
        "send_date": "📅 Enter the date (e.g. 2024 or March 2024), or 'no':",
        "send_description": "📝 Add a description (or 'no'):",
        "added": "✅ Graffiti submitted for moderation! It will appear on the map after review.",
        "cancelled": "Action cancelled.",
        "no_graffiti": "No graffiti on the map yet. Add the first one!",
        "open_map": "Tap the button to open the map:",
        "search_prompt": "Enter an artist name or keyword:",
        "search_empty": "Nothing found for '{}'.",
        "search_found": "Graffiti found: {}",
        "search_done": "Search complete.",
        "send_photo_please": "Please send a photo.",
        "send_location_please": "Please send a location (📎 → Location).",
        "admin_only": "This feature is for admins only.",
        "choose_language": "🌐 Choose language:",
        "language_set": "Language set: English 🇬🇧",
        "no_description": "No description",
        "graffiti_count": "{} graffiti on the map:",
        "delete": "🗑 Delete",
        "confirm_delete": "✅ Yes, delete",
        "cancel_delete_btn": "❌ Cancel",
        "deleted": "🗑 DELETED",
        "approved": "✅ APPROVED",
        "rejected": "❌ REJECTED",
        "confirm_deletion": "Confirm deletion",
        "no": "no",
        "unknown_author": "Unknown",
        "unknown_date": "Unknown",
        "btn_stats": "📊 Stats",
        "stats": "📊 Statistics:\n\n🎨 On map: {approved}\n⏳ Pending: {pending}\n📦 Total: {total}",
        "top_users": "\n\n🏆 Top contributors:",
        "users_count": "\n\n👥 Users: {}",
        "top_liked": "\n\n❤️ Most popular:",
        "btn_gallery": "🖼 Gallery",
        "gallery_empty": "No graffiti yet.",
        "gallery_counter": "{} of {}",
        "send_city": "🏙 Enter the city name (e.g. Tbilisi, Berlin, Tokyo):",
    },
    "ka": {
        "start": "გამარჯობა! მე ვარ ბოტი «გრაფიტის მსოფლიო რუკა» 🌍\n\nაირჩიეთ მოქმედება:",
        "btn_map": "🗺 რუკა",
        "btn_add": "➕ გრაფიტის დამატება",
        "btn_search": "🔍 ძიება",
        "btn_manage": "⚙️ მართვა",
        "btn_cancel": "❌ გაუქმება",
        "btn_language": "🌐 ენა",
        "btn_open_map": "🗺 რუკის გახსნა",
        "send_photo": "📸 გამოაგზავნეთ გრაფიტის ფოტო:",
        "send_location": "📍 ახლა გამოაგზავნეთ გრაფიტის მდებარეობა.\n\nდააჭირეთ 📎 → მდებარეობა → აირჩიეთ წერტილი რუკაზე.",
        "send_author": "✍️ შეიყვანეთ ავტორის სახელი (ან «არა» თუ უცნობია):",
        "send_date": "📅 შეიყვანეთ თარიღი (მაგ: 2024 ან მარტი 2024), ან «არა»:",
        "send_description": "📝 დაამატეთ აღწერა (ან «არა»):",
        "added": "✅ გრაფიტი გაიგზავნა მოდერაციაზე! შემოწმების შემდეგ გამოჩნდება რუკაზე.",
        "cancelled": "მოქმედება გაუქმებულია.",
        "no_graffiti": "რუკაზე ჯერ არ არის გრაფიტი. დაამატეთ პირველი!",
        "open_map": "დააჭირეთ ღილაკს რუკის გასახსნელად:",
        "search_prompt": "შეიყვანეთ ავტორის სახელი ან საკვანძო სიტყვა:",
        "search_empty": "მოთხოვნით «{}» ვერაფერი მოიძებნა.",
        "search_found": "ნაპოვნია გრაფიტი: {}",
        "search_done": "ძიება დასრულებულია.",
        "send_photo_please": "გთხოვთ გამოაგზავნოთ ფოტო.",
        "send_location_please": "გთხოვთ გამოაგზავნოთ მდებარეობა (📎 → მდებარეობა).",
        "admin_only": "ეს ფუნქცია მხოლოდ ადმინისტრატორისთვისაა.",
        "choose_language": "🌐 Choose language:",
        "language_set": "ენა დაყენებულია: ქართული 🇬🇪",
        "no_description": "აღწერა არ არის",
        "graffiti_count": "რუკაზე {} გრაფიტი:",
        "delete": "🗑 წაშლა",
        "confirm_delete": "✅ დიახ, წაშლა",
        "cancel_delete_btn": "❌ გაუქმება",
        "deleted": "🗑 წაშლილია",
        "approved": "✅ დამტკიცებულია",
        "rejected": "❌ უარყოფილია",
        "confirm_deletion": "დაადასტურეთ წაშლა",
        "no": "არა",
        "unknown_author": "უცნობი",
        "unknown_date": "უცნობია",
        "btn_stats": "📊 სტატისტიკა",
        "stats": "📊 სტატისტიკა:\n\n🎨 რუკაზე: {approved}\n⏳ მოდერაციაზე: {pending}\n📦 სულ: {total}",
        "top_users": "\n\n🏆 ტოპ მონაწილეები:",
        "users_count": "\n\n👥 მომხმარებლები: {}",
        "top_liked": "\n\n❤️ ყველაზე პოპულარული:",
        "btn_gallery": "🖼 გალერეა",
        "gallery_empty": "გრაფიტი ჯერ არ არის.",
        "gallery_counter": "{} / {}",
        "send_city": "🏙 შეიყვანეთ ქალაქის სახელი (მაგ: თბილისი, ბერლინი, ტოკიო):",
    },
    "es": {
        "start": "¡Hola! Soy el bot «Mapa Mundial de Graffiti» 🌍\n\nElige una acción:",
        "btn_map": "🗺 Mapa",
        "btn_add": "➕ Añadir graffiti",
        "btn_search": "🔍 Buscar",
        "btn_manage": "⚙️ Gestionar",
        "btn_cancel": "❌ Cancelar",
        "btn_language": "🌐 Idioma",
        "btn_open_map": "🗺 Abrir mapa",
        "send_photo": "📸 Envía una foto del graffiti:",
        "send_location": "📍 Ahora envía la ubicación del graffiti.\n\nToca el clip 📎 → Ubicación → elige un punto en el mapa.",
        "send_author": "✍️ Escribe el nombre del artista (o 'no' si es desconocido):",
        "send_date": "📅 Escribe la fecha (ej: 2024 o marzo 2024), o 'no':",
        "send_description": "📝 Añade una descripción (o 'no'):",
        "added": "✅ ¡Graffiti enviado para moderación! Aparecerá en el mapa tras la revisión.",
        "cancelled": "Acción cancelada.",
        "no_graffiti": "Aún no hay graffiti en el mapa. ¡Añade el primero!",
        "open_map": "Toca el botón para abrir el mapa:",
        "search_prompt": "Escribe el nombre del artista o una palabra clave:",
        "search_empty": "No se encontró nada para '{}'.",
        "search_found": "Graffiti encontrados: {}",
        "search_done": "Búsqueda completada.",
        "send_photo_please": "Por favor, envía una foto.",
        "send_location_please": "Por favor, envía una ubicación (📎 → Ubicación).",
        "admin_only": "Esta función es solo para administradores.",
        "choose_language": "🌐 Choose language:",
        "language_set": "Idioma establecido: Español 🇪🇸",
        "no_description": "Sin descripción",
        "graffiti_count": "{} graffiti en el mapa:",
        "delete": "🗑 Eliminar",
        "confirm_delete": "✅ Sí, eliminar",
        "cancel_delete_btn": "❌ Cancelar",
        "deleted": "🗑 ELIMINADO",
        "approved": "✅ APROBADO",
        "rejected": "❌ RECHAZADO",
        "confirm_deletion": "Confirmar eliminación",
        "no": "no",
        "unknown_author": "Desconocido",
        "unknown_date": "Desconocida",
        "btn_stats": "📊 Estadísticas",
        "stats": "📊 Estadísticas:\n\n🎨 En el mapa: {approved}\n⏳ Pendientes: {pending}\n📦 Total: {total}",
        "top_users": "\n\n🏆 Mejores contribuidores:",
        "users_count": "\n\n👥 Usuarios: {}",
        "top_liked": "\n\n❤️ Más populares:",
        "btn_gallery": "🖼 Galería",
        "gallery_empty": "Aún no hay graffiti.",
        "gallery_counter": "{} de {}",
        "send_city": "🏙 Entre le nom de la ville (ex : Tbilissi, Berlin, Tokyo) :",
    },
    "fr": {
        "start": "Salut ! Je suis le bot «Carte Mondiale du Graffiti» 🌍\n\nChoisis une action :",
        "btn_map": "🗺 Carte",
        "btn_add": "➕ Ajouter un graffiti",
        "btn_search": "🔍 Rechercher",
        "btn_manage": "⚙️ Gérer",
        "btn_cancel": "❌ Annuler",
        "btn_language": "🌐 Langue",
        "btn_open_map": "🗺 Ouvrir la carte",
        "send_photo": "📸 Envoie une photo du graffiti :",
        "send_location": "📍 Maintenant envoie la localisation du graffiti.\n\nAppuie sur le trombone 📎 → Position → choisis un point sur la carte.",
        "send_author": "✍️ Entre le nom de l'artiste (ou 'non' si inconnu) :",
        "send_date": "📅 Entre la date (ex : 2024 ou mars 2024), ou 'non' :",
        "send_description": "📝 Ajoute une description (ou 'non') :",
        "added": "✅ Graffiti envoyé pour modération ! Il apparaîtra sur la carte après vérification.",
        "cancelled": "Action annulée.",
        "no_graffiti": "Pas encore de graffiti sur la carte. Ajoute le premier !",
        "open_map": "Appuie sur le bouton pour ouvrir la carte :",
        "search_prompt": "Entre un nom d'artiste ou un mot-clé :",
        "search_empty": "Rien trouvé pour «{}».",
        "search_found": "Graffiti trouvés : {}",
        "search_done": "Recherche terminée.",
        "send_photo_please": "Envoie une photo, s'il te plaît.",
        "send_location_please": "Envoie une localisation, s'il te plaît (📎 → Position).",
        "admin_only": "Cette fonction est réservée aux administrateurs.",
        "choose_language": "🌐 Choose language:",
        "language_set": "Langue définie : Français 🇫🇷",
        "no_description": "Pas de description",
        "graffiti_count": "{} graffiti sur la carte :",
        "delete": "🗑 Supprimer",
        "confirm_delete": "✅ Oui, supprimer",
        "cancel_delete_btn": "❌ Annuler",
        "deleted": "🗑 SUPPRIMÉ",
        "approved": "✅ APPROUVÉ",
        "rejected": "❌ REJETÉ",
        "confirm_deletion": "Confirmer la suppression",
        "no": "non",
        "unknown_author": "Inconnu",
        "unknown_date": "Inconnue",
        "btn_stats": "📊 Statistiques",
        "stats": "📊 Statistiques :\n\n🎨 Sur la carte : {approved}\n⏳ En attente : {pending}\n📦 Total : {total}",
        "top_users": "\n\n🏆 Meilleurs contributeurs :",
        "users_count": "\n\n👥 Utilisateurs : {}",
        "top_liked": "\n\n❤️ Les plus populaires :",
        "btn_gallery": "🖼 Galerie",
        "gallery_empty": "Pas encore de graffiti.",
        "gallery_counter": "{} sur {}",
        "send_city": "🏙 Entre le nom de la ville (ex : Tbilissi, Berlin, Tokyo) :",
    },
    "de": {
        "start": "Hallo! Ich bin der «Welt-Graffiti-Karte» Bot 🌍\n\nWähle eine Aktion:",
        "btn_map": "🗺 Karte",
        "btn_add": "➕ Graffiti hinzufügen",
        "btn_search": "🔍 Suchen",
        "btn_manage": "⚙️ Verwalten",
        "btn_cancel": "❌ Abbrechen",
        "btn_language": "🌐 Sprache",
        "btn_open_map": "🗺 Karte öffnen",
        "send_photo": "📸 Sende ein Foto des Graffiti:",
        "send_location": "📍 Sende jetzt den Standort des Graffiti.\n\nTippe auf die Klammer 📎 → Standort → wähle einen Punkt auf der Karte.",
        "send_author": "✍️ Gib den Namen des Künstlers ein (oder 'nein' wenn unbekannt):",
        "send_date": "📅 Gib das Datum ein (z.B. 2024 oder März 2024), oder 'nein':",
        "send_description": "📝 Füge eine Beschreibung hinzu (oder 'nein'):",
        "added": "✅ Graffiti zur Moderation eingereicht! Es erscheint nach der Prüfung auf der Karte.",
        "cancelled": "Aktion abgebrochen.",
        "no_graffiti": "Noch kein Graffiti auf der Karte. Füge das erste hinzu!",
        "open_map": "Tippe auf den Button, um die Karte zu öffnen:",
        "search_prompt": "Gib einen Künstlernamen oder ein Stichwort ein:",
        "search_empty": "Nichts gefunden für '{}'.",
        "search_found": "Graffiti gefunden: {}",
        "search_done": "Suche abgeschlossen.",
        "send_photo_please": "Bitte sende ein Foto.",
        "send_location_please": "Bitte sende einen Standort (📎 → Standort).",
        "admin_only": "Diese Funktion ist nur für Administratoren.",
        "choose_language": "🌐 Choose language:",
        "language_set": "Sprache eingestellt: Deutsch 🇩🇪",
        "no_description": "Keine Beschreibung",
        "graffiti_count": "{} Graffiti auf der Karte:",
        "delete": "🗑 Löschen",
        "confirm_delete": "✅ Ja, löschen",
        "cancel_delete_btn": "❌ Abbrechen",
        "deleted": "🗑 GELÖSCHT",
        "approved": "✅ GENEHMIGT",
        "rejected": "❌ ABGELEHNT",
        "confirm_deletion": "Löschung bestätigen",
        "no": "nein",
        "unknown_author": "Unbekannt",
        "unknown_date": "Unbekannt",
        "btn_stats": "📊 Statistiken",
        "stats": "📊 Statistiken:\n\n🎨 Auf der Karte: {approved}\n⏳ Ausstehend: {pending}\n📦 Gesamt: {total}",
        "top_users": "\n\n🏆 Top-Beitragende:",
        "users_count": "\n\n👥 Benutzer: {}",
        "top_liked": "\n\n❤️ Am beliebtesten:",
        "btn_gallery": "🖼 Galerie",
        "gallery_empty": "Noch kein Graffiti.",
        "gallery_counter": "{} von {}",
        "send_city": "🏙 Gib den Stadtnamen ein (z.B. Tbilisi, Berlin, Tokio):",
    },
}

user_languages = {}


def get_text(user_id, key):
    lang = user_languages.get(user_id, "ru")
    return TEXTS[lang].get(key, TEXTS["ru"][key])


def set_language(user_id, lang):
    user_languages[user_id] = lang


def get_language(user_id):
    return user_languages.get(user_id, "ru")