TEXTS = {
    "ru": {
        "start": "Привет! Я бот «Мировая карта граффити» 🌍\n\nВыберите действие:",,
        "btn_map": "🗺 Карта",
        "btn_add": "➕ Добавить граффити",
        "btn_search": "🔍 Поиск",
        "btn_manage": "⚙️ Управление",
        "btn_cancel": "❌ Отмена",
        "btn_language": "🌐 Язык",
        "btn_open_map": "🗺 Открыть карту",
        "send_photo": "📸 Отправьте фото граффити:",
        "send_location": "📍 Теперь отправьте геолокацию граффити.\n\nНажмите скрепку 📎 → Геолокация → выберите точку на карте.",
        "send_author": "✍️ Введите никнейм автора граффити (или напишите «нет», если неизвестен):",
        "send_date": "📅 Введите дату нанесения (например: 2024 или март 2024), или «нет»:",
        "send_description": "📝 Добавьте описание граффити (или «нет»):",
        "added": "✅ Граффити отправлено на модерацию! После проверки оно появится на карте.",
        "cancelled": "Действие отменено.",
        "no_graffiti": "На карте пока нет граффити. Добавьте первое!",
        "open_map": "Нажмите кнопку, чтобы открыть карту:",
        "search_prompt": "Введите имя автора или ключевое слово:",
        "search_empty": "По запросу «{}» ничего не найдено.",
        "search_found": "Найдено граффити: {}",
        "search_done": "Поиск завершён.",
        "send_photo_please": "Пожалуйста, отправьте именно фото.",
        "send_location_please": "Пожалуйста, отправьте именно геолокацию (📎 → Геолокация).",
        "admin_only": "Эта функция доступна только администратору.",
        "choose_language": "🌐 Выберите язык / Choose language / აირჩიეთ ენა:",
        "language_set": "Язык установлен: Русский 🇷🇺",
        "no_description": "Нет описания",
        "graffiti_count": "На карте {} граффити:",
        "delete": "🗑 Удалить",
        "confirm_delete": "✅ Да, удалить",
        "cancel_delete_btn": "❌ Отмена",
        "deleted": "🗑 УДАЛЕНО",
        "approved": "✅ ОДОБРЕНО",
        "rejected": "❌ ОТКЛОНЕНО",
        "confirm_deletion": "Подтвердите удаление",
        "no": "нет",
        "unknown_author": "Неизвестен",
        "unknown_date": "Неизвестна",
        "btn_stats": "📊 Статистика",
        "stats": "📊 Статистика:\n\n🎨 На карте: {approved}\n⏳ На модерации: {pending}\n📦 Всего: {total}",
        "top_users": "\n\n🏆 Топ участников:",
        "users_count": "\n\n👥 Пользователей: {}",
        "top_liked": "\n\n❤️ Самые популярные:",
        "btn_gallery": "🖼 Галерея",
        "gallery_empty": "Граффити пока нет.",
        "gallery_counter": "{} из {}",
    },
    "en": {
        "start": "გამარჯობა! მე ვარ ბოტი «გრაფიტის მსოფლიო რუკა» 🌍\n\nაირჩიეთ მოქმედება:",
        "btn_map": "🗺 Map",
        "btn_add": "➕ Add graffiti",
        "btn_search": "🔍 Search",
        "btn_manage": "⚙️ Manage",
        "btn_cancel": "❌ Cancel",
        "btn_language": "🌐 Language",
        "btn_open_map": "🗺 Open map",
        "send_photo": "📸 Send a photo of the graffiti:",
        "send_location": "📍 Now send the graffiti location.\n\nTap the clip 📎 → Location → choose a point on the map.",
        "send_author": "✍️ Enter the artist's name (or 'no' if unknown):",
        "send_date": "📅 Enter the date (e.g. 2024 or March 2024), or 'no':",
        "send_description": "📝 Add a description (or 'no'):",
        "added": "✅ Graffiti submitted for moderation! It will appear on the map after review.",
        "cancelled": "Action cancelled.",
        "no_graffiti": "No graffiti on the map yet. Add the first one!",
        "open_map": "Tap the button to open the map:",
        "search_prompt": "Enter an artist name or keyword:",
        "search_empty": "Nothing found for '{}'.",
        "search_found": "Graffiti found: {}",
        "search_done": "Search complete.",
        "send_photo_please": "Please send a photo.",
        "send_location_please": "Please send a location (📎 → Location).",
        "admin_only": "This feature is for admins only.",
        "choose_language": "🌐 Выберите язык / Choose language / აირჩიეთ ენა:",
        "language_set": "Language set: English 🇬🇧",
        "no_description": "No description",
        "graffiti_count": "{} graffiti on the map:",
        "delete": "🗑 Delete",
        "confirm_delete": "✅ Yes, delete",
        "cancel_delete_btn": "❌ Cancel",
        "deleted": "🗑 DELETED",
        "approved": "✅ APPROVED",
        "rejected": "❌ REJECTED",
        "confirm_deletion": "Confirm deletion",
        "no": "no",
        "unknown_author": "Unknown",
        "unknown_date": "Unknown",
        "btn_stats": "📊 Stats",
        "stats": "📊 Statistics:\n\n🎨 On map: {approved}\n⏳ Pending: {pending}\n📦 Total: {total}",
        "top_users": "\n\n🏆 Top contributors:",
        "users_count": "\n\n👥 Users: {}",
        "top_liked": "\n\n❤️ Most popular:",
        "btn_gallery": "🖼 Gallery",
        "gallery_empty": "No graffiti yet.",
        "gallery_counter": "{} of {}",
    },
    "ka": {
        "start": "გამარჯობა! მე ვარ ბოტი «თბილისის გრაფიტი» 🎨\n\nაირჩიეთ მოქმედება:",
        "btn_map": "🗺 რუკა",
        "btn_add": "➕ გრაფიტის დამატება",
        "btn_search": "🔍 ძიება",
        "btn_manage": "⚙️ მართვა",
        "btn_cancel": "❌ გაუქმება",
        "btn_language": "🌐 ენა",
        "btn_open_map": "🗺 რუკის გახსნა",
        "send_photo": "📸 გამოაგზავნეთ გრაფიტის ფოტო:",
        "send_location": "📍 ახლა გამოაგზავნეთ გრაფიტის მდებარეობა.\n\nდააჭირეთ 📎 → მდებარეობა → აირჩიეთ წერტილი რუკაზე.",
        "send_author": "✍️ შეიყვანეთ ავტორის სახელი (ან «არა» თუ უცნობია):",
        "send_date": "📅 შეიყვანეთ თარიღი (მაგ: 2024 ან მარტი 2024), ან «არა»:",
        "send_description": "📝 დაამატეთ აღწერა (ან «არა»):",
        "added": "✅ გრაფიტი გაიგზავნა მოდერაციაზე! შემოწმების შემდეგ გამოჩნდება რუკაზე.",
        "cancelled": "მოქმედება გაუქმებულია.",
        "no_graffiti": "რუკაზე ჯერ არ არის გრაფიტი. დაამატეთ პირველი!",
        "open_map": "დააჭირეთ ღილაკს რუკის გასახსნელად:",
        "search_prompt": "შეიყვანეთ ავტორის სახელი ან საკვანძო სიტყვა:",
        "search_empty": "მოთხოვნით «{}» ვერაფერი მოიძებნა.",
        "search_found": "ნაპოვნია გრაფიტი: {}",
        "search_done": "ძიება დასრულებულია.",
        "send_photo_please": "გთხოვთ გამოაგზავნოთ ფოტო.",
        "send_location_please": "გთხოვთ გამოაგზავნოთ მდებარეობა (📎 → მდებარეობა).",
        "admin_only": "ეს ფუნქცია მხოლოდ ადმინისტრატორისთვისაა.",
        "choose_language": "🌐 Выберите язык / Choose language / აირჩიეთ ენა:",
        "language_set": "ენა დაყენებულია: ქართული 🇬🇪",
        "no_description": "აღწერა არ არის",
        "graffiti_count": "რუკაზე {} გრაფიტი:",
        "delete": "🗑 წაშლა",
        "confirm_delete": "✅ დიახ, წაშლა",
        "cancel_delete_btn": "❌ გაუქმება",
        "deleted": "🗑 წაშლილია",
        "approved": "✅ დამტკიცებულია",
        "rejected": "❌ უარყოფილია",
        "confirm_deletion": "დაადასტურეთ წაშლა",
        "no": "არა",
        "unknown_author": "უცნობი",
        "unknown_date": "უცნობია",
        "btn_stats": "📊 სტატისტიკა",
        "stats": "📊 სტატისტიკა:\n\n🎨 რუკაზე: {approved}\n⏳ მოდერაციაზე: {pending}\n📦 სულ: {total}",
        "top_users": "\n\n🏆 ტოპ მონაწილეები:",
        "users_count": "\n\n👥 მომხმარებლები: {}",
        "top_liked": "\n\n❤️ ყველაზე პოპულარული:",
        "btn_gallery": "🖼 გალერეა",
        "gallery_empty": "გრაფიტი ჯერ არ არის.",
        "gallery_counter": "{} / {}",
    }
}

user_languages = {}


def get_text(user_id, key):
    lang = user_languages.get(user_id, "en")
    return TEXTS[lang].get(key, TEXTS["en"][key])


def set_language(user_id, lang):
    user_languages[user_id] = lang


def get_language(user_id):
    return user_languages.get(user_id, "en")